### ISSUE TITLE
How does this improve on Envify?

### ISSUE THREAD

**Issue by percula** [petercinibulk/envied#1]
Hi! I just found this library because it was featured in the FlutterTap newsletter. I'm curious, what was your motivation to create this plugin and how does it differ from Envify, the plugin you based it on?

Sorry this isn't an "issue", I didn't know where to ask this.

**Comment by archie20** [comment]
> Hi! I just found this library because it was featured in the FlutterTap newsletter. I'm curious, what was your motivation to create this plugin and how does it differ from Envify, the plugin you based it on?
> 
> Sorry this isn't an "issue", I didn't know where to ask this.

Envify seems to be abandoned so I guess this is an updated version to work with Flutter 3.0

**Comment by percula** [comment]
Ah, great. I had a feeling that might be the case. Thanks for the reply and
for maintaining this library!

**Comment by petercinibulk** [comment]
@percula It is a mix of Envify being abandoned and pretty opinionated in how you name your variables in env file. My goal is to have this library be as flexible as possible.
