### ISSUE TITLE
DefaultValue override env value - Expected ?

### ISSUE THREAD

**Issue by heralight** [petercinibulk/envied#103]
Hi!
Thank you for your library.

regarding defalutValue attribute parameter, I don't understand the purpose of it. 
## actual behavior

From my test, If I do:
```dart
  @EnviedField(defaultValue: "toto")
  static const String myvar = _Config.myvar;
```
and inside .env :
```sh
 myvar="AAAA"
```

at runtime myvar == "toto".

## Expected behavior
at runtime myvar == "AAAA".
if .env is empty, mut be at runtime myvar == "toto"

## Conclusion

if defalutValue is to set constant value that override everything, a better name could be "finalValue" or "primaryValue", ...etc with some extra documentation.

Thank you for your clarification,

Best regards, 

Alexandre

**Comment by techouse** [comment]
Hey,

[This](https://github.com/petercinibulk/envied/pull/14) might provide some clues. I assume it's there when the value is completely missing from the `.env`.

**Comment by heralight** [comment]
Thank you !
