### ISSUE TITLE
Values not updated when changed in .env file. Caching bug

### ISSUE THREAD

**Issue by ospaarmann** [petercinibulk/envied#107]
There seems to be a bug in the generator. When I change the values in the underlying `.env` file, delete the `env.g.dart` file and run the generator, the old values are written to the generated file.

Consider this code:

```dart
// lib/env/env.dart

import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env.dev', useConstantCase: true)
final class Env {
  @EnviedField()
  static const String apiBaseUrl = _Env.apiBaseUrl;
}
```

```
# .env.dev
API_BASE_URL="dev.example.com"
```

```
# .env.prod
API_BASE_URL="prod.example.com"
```

I am using two `.env` files: `.env.prod` and `.env.dev`. 

**How to reproduce the bug**

1. Update the value in `.env.dev` from "dev.example.com" to "devnew.example.com"
2. Delete `env.g.dart`
3. Run the generator

**Expected result:**

The value in `env.g.dart` is now "devnew.example.com"

**Actual result:**

The value is still "dev.example.com"

**When it works:**

1. Changing the path from `.env.dev` to `.env.prod` and back
2. Run `flutter clean` and then generate again with `dart run build_runner watch --delete-conflicting-outputs`

It looks to me like there is some caching issue going on.

**Version:** 0.5.3

**Comment by ospaarmann** [comment]
Sorry, I just found this issue in "Known Issues" in your readme...

**Comment by simplenotezy** [comment]
I know this is a known issue, but can we do a workaround? I like to have strictly typed ENV files, however, this is actually so critical, that I might need to switch to another approach/library.

@petercinibulk

**Comment by techouse** [comment]
> I know this is a known issue, but can we do a workaround?

Well, for starters, you could suggest one.

>  might need to switch to another approach/library

What's stopping you?

**Comment by simplenotezy** [comment]
For anybody else looking for a solution, I've switched to using `flutter_dotenv` and a similar approach can be achieved using this code:

```diff
// lib/env/env.dart

+import 'package:flutter_dotenv/flutter_dotenv.dart';
-import 'package:envied/envied.dart';

-part 'env.g.dart';

-@Envied(path: '.env.dev', useConstantCase: true)
final class Env {
-  @EnviedField()
-  static const String apiBaseUrl = _Env.apiBaseUrl;
+  final String apiBaseUrl = dotenv.maybeGet('API_BASE_URL') ?? 'https://localhost:3000';
}
```

And to fetch:

```diff
-const apiBaseUrl = Env.apiBaseUrl;
+final apiBaseUrl = Env().apiBaseUrl;
