### ISSUE TITLE
Question can the obfuscated env value deobfuscated?

### ISSUE THREAD

**Issue by AngDrew** [petercinibulk/envied#108]
i was reading the generation logic, i don't quite understand, but what i see, it is using Random.secure().
first, how dart can read the obfuscated value?
second, can other people (pentester) deobfuscate the value?

**Comment by AngDrew** [comment]
so this package is not safe to save API Keys? @techouse

**Comment by techouse** [comment]
I think this has been said before, but please read [this](https://stackoverflow.com/questions/36673154/best-practices-for-api-key-and-secret-in-bundled-in-app) again before you leak any sensitive secrets.
