### ISSUE TITLE
[Question] Best practice for CI/CD?

### ISSUE THREAD

**Issue by callmephil** [petercinibulk/envied#115]
I'm trying to use envied with CI/CD (Bitbucket Pipeline & Codemagic) and I'm unsure how to handle the file generation process.

It says in the doc that: 
```
IMPORTANT! Add both .env and env.g.dart files to your .gitignore file, otherwise, you might expose your environment variables.
```

So if I can't publish the env.g.dart it mean that I need to generate it using a pre-build? This will also be true for the .env file right? **Is it the recommended approach?**

**Comment by techouse** [comment]
Here's how I usually handle this:

1. add all your secrets and/or variables to [Github Secrets](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions)
2. in your Github actions run the code generation to generate `env.g.dart` using
```bash
dart run build_runner build --delete-conflicting-outputs
```
3. once all the files have been generated **THEN** build your app
4. upload your app to the app stores
5. delete all/any generated files / token files / builds etc in order not to expose any secrets using, i.e.
```yaml
- name: Clean up
  id: clean_up
  if: ${{ always() }}
  run: |
    rm -rf /opt/gcp_key.json
    rm -rf $RUNNER_TEMP/google_play_service_account.json
    rm -rf $RUNNER_TEMP/upload_keystore.jks
    rm -rf env/.env*
    rm -rf android/key.properties
    rm -rf android/app/secrets/*.properties
    rm -rf $RUNNER_TEMP/artifacts*
    rm -rf $NATIVE_DEBUG_SYMBOLS_PATH
    if command -v flutter &>/dev/null; then
      flutter pub run build_runner clean
      flutter clean
    fi
    rm -rf build
    rm -rf debug_info
```
