### ISSUE TITLE
[Feature Request]Can optional parameters be supported?

### ISSUE THREAD

**Issue by kkoken** [petercinibulk/envied#12]
Can **envied** support optional parameters when we use `obfuscate` ? Like `maybeGet` in [dotEnv](https://pub.dev/packages/flutter_dotenv)
Or Could we assign a value using `@Default` decorator?

**Comment by petercinibulk** [comment]
@kkoken Could you provide a simple example of what you mean?

**Comment by kkoken** [comment]
@petercinibulk can you check #14. I have created PR with my personal git account

**Comment by ElteHupkes** [comment]
This would be practical to have. I would personally expect it to look similar to the `JsonKey` annotation:

```dart
@Envied()
abstract class Env {
  @EnviedField(varName: 'MY_VAR', defaultValue: "My Default Value")
  static const myVar = _Env.myVar;
}
```

That might make more sense than using another annotator.
