### ISSUE TITLE
Envied with firebase remote config feature as a parameter

### ISSUE THREAD

**Issue by suryamin** [petercinibulk/envied#18]
Hi,

It is not an issue but a suggestion to add a feature. My apologies if this is not the forum to post a suggestion.

Would it be possible to store part of obfuscation, either the key or the data into Firebase Remote Config to make it more secure?
It would be nice if it can be archived with parameter control.

Thank you.
Best Regards

**Comment by techouse** [comment]
@suryamin can you please elaborate? AFAIK all you have to do is set up the Google Services JSON and get the remote config as explained here https://firebase.google.com/docs/remote-config/get-started?platform=flutter

**Comment by suryamin** [comment]
Please kindly give me the firebase link, I can set it up.

**Comment by suryamin** [comment]
Remote Config is part of Firebase, to use it needs to active Firebase account with an email.

**Comment by suryamin** [comment]
Hi,

probably just consider using flutter_secure_storage instead of firebase.
flutter_secure_storage has been built in with encryption and stored at local and it does not depend on anything. 
Firebase on the other hand depends on the server.
I use it as the cache and it's a pretty good package.

Thank you.
