### ISSUE TITLE
System variable priority

### ISSUE THREAD

**Issue by KestasVenslauskas** [petercinibulk/envied#21]
Can we have an option to give priority to system variables over .env file?

**Comment by techouse** [comment]
@KestasVenslauskas can you give an example?

**Comment by KestasVenslauskas** [comment]
@techouse 
Imagine having .env file in your repo for development environment setup. But you want to build a prod version on CI machine where all your prod variables are in. This way you wouldstill get development environment build because .env file takes priority  over system variables.

**Comment by techouse** [comment]
@KestasVenslauskas So you mean something like `--dart-define`? Can you give a **concrete** example?

**Comment by KestasVenslauskas** [comment]
no like `export SOME_VAR=foo` & `dart run build_runner build`

Here is the issue:
https://github.com/petercinibulk/envied/blob/62fa2e9d2acdaa7f3e8a85193bbd1445c3770535/packages/envied_generator/lib/src/generator.dart#L101

It prioritizes env field from specified file & not my export

**Comment by techouse** [comment]
OK, I think we can discuss switching the order @petercinibulk @ThexXTURBOXx

**Comment by ThexXTURBOXx** [comment]
Switching the order does not make sense since the .env file is the most local object to pull values from and hence should be prioritised.
Also, switching the order would result in a huge breaking change.
However, one could think about some flag that can be defined in order to force prioritising system environment variables.

**Comment by KestasVenslauskas** [comment]
A new flag in annotations would be great!

**Comment by techouse** [comment]
@KestasVenslauskas since you're already wrangling shell to pass in these ENV params, what if you used `sed` instead to set them up before compliing them into `*.g.dart` files?

i.e.

```bash
#!/usr/bin/env bash
sed -i "s/MY_ENV=.*/MY_ENV=$SOME_BASH_VALUE/" path/to/.env
dart run build_runner build
```

Looks fairly straightforward in an automation script

**Comment by techouse** [comment]
@KestasVenslauskas please use the technique used above, alternatively, delete the set value from your `.env` and rely on shell ENV vars. Switching the current priority order would be too much of a breaking change.
