### ISSUE TITLE
Causes regen of other packages using build_runner

### ISSUE THREAD

**Issue by mobikats** [petercinibulk/envied#22]
Returning to an older project, and running 

`flutter pub run build_runner build`

And running into an issue with other files that get regenerated by this command too. I was wondering if this package could be specifically passed as argument so that it only this package was rebuilt with build_runner?
eg
`flutter pub run build_runner build envied`

Or similar?

Apologies if that's not feasible or how build_runner should be used, but I hope you see the issue - it would be ideal to be able to specifically regenerate the env, and not affect anything else.

**Comment by techouse** [comment]
I think you can use filtering to achieve what you want as explained here https://github.com/dart-lang/build/issues/2815
