### ISSUE TITLE
Null Value Support

### ISSUE THREAD

**Issue by getBoolean** [petercinibulk/envied#25]
Null-value support would be appreciated. This was previously implemented in a PR for `envify` but was never merged, https://github.com/frencojobs/envify/pull/21 (though I do not know the details of how it was implemented)

I am aware of `defaultValue` on `@EnviedField`, but to my understanding, this does not support null.

## Proposal

Support the following code. `key1` will be set to `null` if the environment variable is not available instead of the build script failing.

```dart
@EnviedField(varName: 'KEY1')
final String? key1 = _Env.key1;
```

This currently fails with the following
```bash
Environment variable not found for field `key1`.
package:env/src/env/debug_env.dart:16:17
   ╷
16 │   final String? key1 = _Env.key1;
   │                 ^^^^
   ╵
```

## Use Case

In my project, I would like to make cloud services optional if someone wants to build from source, and I want to remove the step of specifying the environment variables. A hacky workaround is to set the default value to an empty string, but this means that I need to remember to check if the value is an empty String every time I use the variable.

**Comment by felipecastrosales** [comment]
That sounds interesting to me, as well as pr. 

I was just goind to cite the start as empty solution, but it really can be annoying. You can create an extension to make the use more practical.

**Comment by getBoolean** [comment]
Would it be okay if I try to port the previously mentioned PR by @DebkanchanSamadder to this package?

**Comment by techouse** [comment]
Potentially, however, I do not see the point of a nullable environment variable.

**Comment by getBoolean** [comment]
> Potentially, however, I do not see the point of a nullable environment variable.

I believe it was explained well in the original issue https://github.com/frencojobs/envify/issues/20

For example, it gives us type safety for variables that should only be used in production where as in other modes it'll be null (instead of a default or empty string). In addition to that, if all variables are nullable, creating an .env should be optional.

Though this is something I want, I haven't started work on this yet. it'll take some time to implement/test and I don't want to work on it unless the maintainers are interested in this addition.

**Comment by techouse** [comment]
> I believe it was explained well in the original issue https://github.com/frencojobs/envify/issues/20

I see, it's a niche use case, but nonetheless a nice one to have.

> Though this is something I want, I haven't started work on this yet. it'll take some time to implement/test and I don't want to work on it unless the maintainers are interested in this addition.

Go for it :) Let me know if you need any help.

**Comment by DebkanchanSamadder** [comment]
Author of the original PR here. Since creating that PR my opinions have changed. Now I recommend always having a default value even an empty value rather than null for stability reasons.

But if you want null value support go for it and feel free to copy all my work over.

**Comment by getBoolean** [comment]
@DebkanchanSamadder thanks for the insight, could you elaborate on the stability issues you encountered?

**Comment by getBoolean** [comment]
It was surprisingly easier than expected, thanks to the work done by @DebkanchanSamadder. Currently, I have it implemented in my [fork#null_value_support](https://github.com/getBoolean/envied/tree/feature/null_value_support) branch.

I will create a pull request once I do some more testing. I am most concerned with testing `generateFieldsEncrypted`, it is much more complex so I may have missed something.

**Comment by getBoolean** [comment]
@techouse I have a question about the following code, I want to make sure I don't change too much behavior since this includes some changes to allow dynamic. Should this `key1` use type inference using the `key1` environment variable (don't put a type), or should it force the type to be `dynamic`?

My current implementation is option 1. I believe the implementation by @DebkanchanSamadder does option 2.

Option 1:
```dart
@Envied()
final class Env {
    @EnviedField()
    static const key1 = _Env.key1; // InvalidType, inferred as String
}
...
final class _Env {
  static const key1 = 'foo';
}
```

Option 2:
```dart
@Envied()
final class Env {
    @EnviedField()
    static const key1 = _Env.key1; // inferred as dynamic
}
...
final class _Env {
  static const dynamic key1 = 'foo';
}
```

**Comment by getBoolean** [comment]
Currently on `main`, not specifying a type will fail the generator with the error below. Is that intentional? The readme examples all do not include types, so it would not work if I understand it correctly.

```
Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `InvalidType` is not one of them.
```

**Comment by techouse** [comment]
Well if you look [here](https://github.com/petercinibulk/envied/blob/main/packages/envied_generator/lib/src/generate_field.dart#L18) you'll see why. What other type of data would you want to have in an ENV file? This is why the proposal of nullable values eludes me.

**Comment by getBoolean** [comment]
I dont need other data types, I think the readme example is out of date, I wanted to confirm that.

I can log a warning if a nullable field is not in the environment file, I think that will help with debugging.

My use case is that online services that need an API Key could be disabled automatically if it is not included. This would be really useful for open source, anyone building the app from source wont need to set up an account for that service. Imo, a default value does not make sense for this.

**Comment by getBoolean** [comment]
I want to avoid introducing foot guns to the API. What do you think about having a flag to enable nullability support? If its not enabled, the environment field or a default value would be required (maintaining the current functionality)

**Comment by techouse** [comment]
> I can log a warning if a nullable field is not in the environment file, I think that will help with debugging.

Code generation logs of apps are miles long and it's soo easy to lose a warning in there. Most of the time these warnings just get ignored and IMHO something as important as an environment variable should fail the build process and divert the developer's attention to it ASAP.

> anyone building the app from source wont need to set up an account for that service

Hmm, why not explicitly state which services to enable?

> What do you think about having a flag to enable nullability support?

Yeah, something like an additional annotation which a user has to enable explicitly to trigger this behaviour would help.

**Comment by getBoolean** [comment]
I added the annotation option `allowOptionalFields` to `Envied` and created the PR. I took special care to revert the changed tests and add new ones for nullable support to demonstrate existing functionality is not broken.

**Comment by techouse** [comment]
Cool. Taking a look now.
