### ISSUE TITLE
getting an error when I set obfuscate to true

### ISSUE THREAD

**Issue by abisao1** [petercinibulk/envied#27]
lib/env/env.dart:13:34: Error: Constant evaluation error:
  static const apiBaseUrl = _Env.apiBaseUrl;

**Comment by johnwiese-ms** [comment]
Receiving the same error with the following code:

```
@Envied(path: 'lib/env/.env')
abstract class Env {
  @EnviedField(varName: 'AZURE_MAPS_API_KEY', obfuscate: true)
  static const azureMapsKey = _Env.azureMapsKey;
}
```
if I remove the `obfucsate` then it works fine. 
```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**Comment by abisao1** [comment]
> Seems to work if you make them `final` instead of `const`

Where do I change? Explain

**Comment by JJordani** [comment]
Using @johnwiese-ms code as an example.

the variable `azureMapsKey` should be marked as `final` instead of `constant`


```
@Envied(path: 'lib/env/.env')
abstract class Env {
  @EnviedField(varName: 'AZURE_MAPS_API_KEY', obfuscate: true)
  static final azureMapsKey = _Env.azureMapsKey;
}
```

**Comment by johnwiese-ms** [comment]
ok, got it.  The code is taken directly from the pub.dev page (and just the variable names modified) and the docs so they apparently need to be updated.

https://pub.dev/packages/envied

https://pub.dev/documentation/envied/latest/
