### ISSUE TITLE
Possible error in the example usage: Const variables must be initialized with a constant value. Try changing the initializer to be a constant expression.

### ISSUE THREAD

**Issue by ohsofoxy273** [petercinibulk/envied#36]
For the example given here and on pub.dev, the env vars are initialized as static const, giving me the error "Const variables must be initialized with a constant value. Try changing the initializer to be a constant expression."

Changing const to final fixes the issue. 
So for this class:
`
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'CHAT_GPT_TOKEN', obfuscate: true)
  static const chatGptToken = _Env.chatGptToken;
  @EnviedField(varName: 'CHAT_GPT_TOKEN2', obfuscate: true)
  static final  chatGptToken = _Env.chatGptToken2;
}
`

The second line for chatGptToken2 works, the first line, as given in the example does not.

**Comment by Bus42** [comment]
Same problem. 

```dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: ".env")
abstract class Env {
  @EnviedField(varName: 'SOME_KEY')
  static const apiKey = _Env.SOME_KEY;
}
```

`Const variables must be initialized with a constant value`
`Try changing the initializer to be a constant expression`
`The getter 'SOME_KEY' isn't defined for the type '_Env'`
`Try importing the library that defines 'SOME_KEY', correcting the name to the name of an existing getter, or defining a getter or field named 'SOME_KEY'`

**Comment by Bus42** [comment]
Update: Re-cloning my repo, running `flutter pub get` _before_ running `flutter pub run build_runner build`, and changing the const declaration to final worked for me.

**Comment by Mukul-Ronin** [comment]
I know this is closed but the explanation for not able to use const is because of obfuscate = true , that's why final works

**Comment by techouse** [comment]
The generator should probably throw an error when it encounters a user error like this.

**Comment by Mukul-Ronin** [comment]
@techouse yeah it would be helpful with a meaningful message but i think mentioning it as case in docs should work just fine, cause i landed on this thread after resolving the issue to check history of it
