### ISSUE TITLE
Doesn't work in VM environments

### ISSUE THREAD

**Issue by BottlePumpkin** [petercinibulk/envied#37]
I created an env file in a VM environment (e.g. codemagic) and tried to generate a .g file with the command flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs. 

`
Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `InvalidType` is not one of them.
`

The error occurred continuously.

**Comment by RicharC293** [comment]
Same error here

**Comment by RicharC293** [comment]
@BottlePumpkin  solved here if you have same problem 
[dart analyzer](https://github.com/petercinibulk/envied/pull/38)

**Comment by techouse** [comment]
Duplicate of https://github.com/petercinibulk/envied/issues/40
