### ISSUE TITLE
False errors when running build_runner

### ISSUE THREAD

**Issue by Bus42** [petercinibulk/envied#39]
I added a single environment variable and now the build fails even when I revert the code to its last functional state. I am receiving the following error when I try to run build_runner:
```
[SEVERE] envied_generator:envied on lib/env/env.dart (cached):

Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `InvalidType` is not one of them.
package:someApp/env/env.dart:8:16
  ╷
8 │   static const someKey = _Env.someKey;
  │                ^^^^^^^
  ╵
[SEVERE] Failed after 67ms
```
The key is a String

**Comment by ibrahimbroachwala** [comment]
Any solution @petercinibulk ?

**Comment by themobilecoder** [comment]
Bump! For some reason, this started happening recently for 
```
 envied_generator: ^0.3.0
or
 envied_generator: ^0.3.0+3
```

**Comment by themobilecoder** [comment]
I was able to fix it @Bus42  and @ibrahimbroachwala .

It might be related to the latest Flutter / Dart version, and the type inference is stricter now.

```
[SEVERE] envied_generator:envied on lib/env/env.dart (cached):

Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `InvalidType` is not one of them.
package:someApp/env/env.dart:8:16
  ╷
8 │   static const someKey = _Env.someKey;
  │                ^^^^^^^
  ╵
[SEVERE] Failed after 67ms
```

Can you add `String` before `someKey` and see if it works? So it will be:

```
static const String someKey = _Env.someKey;
```

**Comment by davidsowerby** [comment]
That fixed it for me, was getting the same errors

**Comment by Bus42** [comment]
It failed for me after performing a rebase. I gave up, aborted, wiped out my local repo (losing a full day's work), cloned it again (exact same code) and it ran fine.
