### ISSUE TITLE
Obfuscated envied can only handle types such as `int`, `bool` and `String`. Type `InvalidType` is not one of them.

### ISSUE THREAD

**Issue by paras-28** [petercinibulk/envied#40]
when running command : flutter pub run build_runner build --delete-conflicting-outputs
getting error : Obfuscated envied can only handle types such as `int`, `bool` and `String`. Type `InvalidType` is not one of them.

Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2965], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

List of Dependency in pubspec.yaml 
cupertino_icons: ^1.0.2
  #State Management
  get: ^4.6.5

  #Network Calls
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0

  # Date Formats
  intl: ^0.18.1

 
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  percent_indicator: ^4.2.3
  flutter_html: ^2.2.1
  barcode_widget: ^2.0.4
  url_launcher: ^6.1.11
  logger: ^1.2.2
  flutter_markdown: ^0.6.14
  auto_size_text: ^3.0.0
  path_provider: ^2.0.15
  flutter_share: ^2.0.0
  cached_network_image: ^3.2.3
  connectivity_plus: any
  screen_brightness: ^0.2.2
  timeago: ^3.4.0
  notificare: ^3.5.2
  notificare_inbox: ^3.5.2
  notificare_push: ^3.5.2
  notificare_push_ui: ^3.5.2
  flutter_mailer: ^2.0.2
  firebase_analytics: ^10.4.2
  flutter_image_compress: ^2.0.3
  firebase_dynamic_links: ^5.3.2
  uni_links: ^0.5.1
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  flutter_facebook_auth: 5.0.7
  sign_in_with_apple: ^4.3.0
  flutter_fadein: ^2.0.0
  image_picker: ^0.8.7+5
  uuid: ^3.0.7
  badges: ^3.0.2
  open_mail_app: ^0.4.5
  geolocator: ^9.0.2
  equatable:
  device_info_plus: ^8.1.0
  restart_app: ^1.1.0+2
  envied: ^0.3.0

And in dev dependency : 
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1

**Comment by nfsxreloader** [comment]
Hey @paras-28, I was having this issue and fixed it by adding the type `String` to each variable of the the dart class, e.g.: 

`static final key = _Env.key;` => `static final String key = _Env.key;`.

**Comment by karthikrao5** [comment]
I have this issue too with version 0.3.0+3. I have a boolean env var and i tried changing it to
```
  @EnviedField(varName: "USE_EMULATORS")
  static const const useEmulators = _Env.useEmulators;
```

How do you do this for non string types?
