### ISSUE TITLE
Feature request: Ability to distinguish between prod, dev & testing

### ISSUE THREAD

**Issue by Tomic-Riedel** [petercinibulk/envied#44]
E.g. when adding `@EnviedField()`, it would be good to have something like `varName` (maybe for dev), `varNameProduction` for production and `varNameTesting` for testing. Why would this be helpful: For example, if you have your API endpoint saved in the .env file and have an API endpoint for the dev, testing and prod, you don't have to change it constantly for different environments.

**Comment by techouse** [comment]
You can just make 3 separate files, i.e.

- `.env.prod`
- `.env.dev`
- `.env.testing`

all of them should implement some common `CommonEnvironment` variables and then based on whichever environment you have loaded at the moment, i.e.

```dart
import 'package:flutter/foundation.dart';

if (kDebugMode) {
  return debugEnv();
}

if (kProfileMode) {
   return profileEnv();
}

if (kReleaseMode) {
  return releaseEnv();
}
```

**Comment by Tomic-Riedel** [comment]
Thank you!

**Comment by a1tem** [comment]
The solution described [here ](https://github.com/petercinibulk/envied/issues/109#issuecomment-2277381567)
