### ISSUE TITLE
Can the values of this package be used in android and ios native files?

### ISSUE THREAD

**Issue by dzab5** [petercinibulk/envied#45]
Can we use these variables that are obfuscated in files like the Info.plist or Android Manifest?

**Comment by techouse** [comment]
Unfortunately not. You have to make those separately.

**Comment by dzab5** [comment]
How could one approach something like this? Currently theres no existing way to do it in Flutter?

**Comment by techouse** [comment]
You could write some smart shell script that does it for all 3 platforms (preferably in your CI/CD pipeline). You can probably use Fastlane for all of it.

**Comment by deandreamatias-worldline** [comment]
@dzab5 https://medium.com/@hamzavedatcengiz/environment-variables-in-flutter-using-on-android-and-ios-native-side-3-55ec9d58b985
