### ISSUE TITLE
README.md still uses envName in #usage section, should be varName

### ISSUE THREAD

**Issue by HiggsWRX** [petercinibulk/envied#5]
I don't know what else to point out here other than what is in the title.

I just installed the package (thanks btw!) and after having some trouble getting it to recognize my env var in env.dart, I noticed the linter was complaining that envName was not defined. 
Looking into the package I noticed that now it is called varName, which seemed to fix things. Maybe this was changed recently but README was not updated?

**Comment by petercinibulk** [comment]
@HiggsWRX Thanks for pointing that out! The readme needs to be updated to reflect some recent changes, but I just haven't had the time recently. I wanted to get some of the new updates out to the people who made the pull requests. I'll close out this issue when I update it. 

Sorry for any confusion!

**Comment by techouse** [comment]
I made a PR https://github.com/petercinibulk/envied/pull/8 which fixes the docs.

**Comment by ThexXTURBOXx** [comment]
This can be closed then, I guess :)
