### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by techouse** [petercinibulk/envied#51]
@petercinibulk what's the current procedure of releasing this package? I was thinking that we could set up a [release workflow](https://dart.dev/tools/pub/automated-publishing) just like I have done for one of my Dart packages [here](https://github.com/techouse/alfred_workflow/blob/master/.github/workflows/publish.yml).

I can write the Github action, however, [you'll need to do some steps](https://dart.dev/tools/pub/automated-publishing#configuring-automated-publishing-from-github-actions-on-pubdev) yourself as you are the owner of the package on pub.dev

**Comment by petercinibulk** [comment]
@techouse  I currently do a manual release but I would be open to setting up a workflow. My only concern is that I am using [melo](https://github.com/invertase/melos/blob/main/docs/guides/automated-releases.mdx) to handle the release and changelog. It should work but there might be some limitations. I am more than happy to do those steps if we can figure out a way to get the action working with melos.

**Comment by techouse** [comment]
Should be doable. I'll research how to do it with melos.
