### ISSUE TITLE
Accessing envied values inside build.gradle

### ISSUE THREAD

**Issue by alaincruz06** [petercinibulk/envied#63]
Hi, I'm building an app with multiple flavors (similar to [https://github.com/petercinibulk/envied/issues/16](https://github.com/petercinibulk/envied/issues/16)), and I need to access the Envied class inside my app/build.gradle file as shown in the code below to get the google_maps_api_key - (firebaseAndroidApiKeyDev). Is there a solution actually to solve this? Thanks in advance

`  productFlavors {
        dev {
            dimension "app"
            resValue "string", "app_name", "App Dev"
            resValue "string", "google_maps_api_key", firebaseAndroidApiKeyDev
            applicationIdSuffix ".dev"
        }
       prod{
       //Another config here 
       }
          }
`
I went trough your docs and asked GPT about it but still got no clue on how to solve this.

**Comment by techouse** [comment]
You'll need to set this up differently with specific Android secrets. Check out this answer https://stackoverflow.com/questions/46764175/secure-way-of-storing-secret-credentials.
