### ISSUE TITLE
envied_generator   >=0.3.0+3 depends on   analyzer ^5.1.0 and freezed   >=2.4.2 depends on analyzer   ^6.0.0, freezed >=2.4.2 is   incompatible with   envied_generator.

### ISSUE THREAD

**Issue by khangahs** [petercinibulk/envied#64]
// lib/env/env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'apiKey')
  static final String key1 = _Env.key1;
  @EnviedField(varName: 'apiSecret')
  static final String key2 = _Env.key2;
}

.env:
`apiKey=123456789`

Error on pub add:
`
Because envied_generator
  <0.2.3+1 depends on analyzer
  ^4.1.0 and envied_generator
  >=0.2.3+1 <0.3.0+1 depends
  on analyzer ^5.1.0,
  envied_generator <0.3.0+1
  requires analyzer ^4.1.0 or
  ^5.1.0.
And because envied_generator
  >=0.3.0+1 <0.3.0+2 depends
  on analyzer ^5.12.0 and
  envied_generator >=0.3.0+2
  <0.3.0+3 depends on analyzer
  ^5.11.1, envied_generator
  <0.3.0+3 requires analyzer
  ^4.1.0 or >=5.1.0 <6.0.0.
And because envied_generator
  >=0.3.0+3 depends on
  analyzer ^5.1.0 and freezed
  >=2.4.2 depends on analyzer
  ^6.0.0, freezed >=2.4.2 is
  incompatible with
  envied_generator.
So, because
  my_app depends
  on both freezed ^2.4.3 and
  envied_generator any,
  version solving failed.
  `

**Comment by amin79** [comment]
same problem here.

**Comment by techouse** [comment]
Use dependency overrides until the latest version is published. Alternatively, you can point directly to the Github repo in your pubspec.yaml.

**Comment by eximius313** [comment]
@techouse,
I have just encountered the same problem with riverpod_lint:
```
Because no versions of envied_generator match >0.3.0+3 <0.4.0 and envied_generator 0.3.0+3 depends on analyzer ^5.1.0, envied_generator ^0.3.0+3 requires analyzer ^5.1.0.
And because riverpod_lint >=2.2.1 depends on analyzer ^6.0.0, envied_generator ^0.3.0+3 is incompatible with riverpod_lint >=2.2.1.
So, because poley_rc depends on both riverpod_lint ^2.3.0 and envied_generator ^0.3.0+3, version solving failed.
```

Could you please publish the latest version already?
