### ISSUE TITLE
envied_generator insufficient permissions uploading

### ISSUE THREAD

**Issue by techouse** [petercinibulk/envied#69]
@petercinibulk while the [`envied` release worked](https://pub.dev/packages/envied/changelog#050), the `envied_generator` one failed as it doesn't have enough permissions to publish the package [as you can see in the log](https://github.com/petercinibulk/envied/actions/runs/6761553662/job/18376551075#step:12:59)

```
Insufficient permissions to the resource at the https://pub.dev/ package repository.
You can modify credentials using:
    dart pub token add https://pub.dev/

The calling GitHub Action is not allowed to publish, because: publishing from github is not enabled. See https://dart.dev/go/publishing-from-github
Authentication failed!
```

Can you please set this up on pub.dev the same way you've done for `envied`? Once you do we can [re-run the failed publish job](https://github.com/petercinibulk/envied/actions/runs/6761553662/job/18376551075).

**Comment by petercinibulk** [comment]
Thanks for all your help @techouse. I updated the pub.dev package and reran the failed ci.

**Comment by techouse** [comment]
@petercinibulk cool! All you have to do to release new version is push a tag like `v0.5.1` to master.
