### ISSUE TITLE
The named parameter 'envName' isn't defined.

### ISSUE THREAD

**Issue by jtkeyva** [petercinibulk/envied#7]
All seemed well when running the generator but then I get this error with my code:

`import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env.dev')
abstract class Env {
  @EnviedField(envName: 'MY_KEY')
  static const MY_KEY = _Env.MY_KEY;
  @EnviedField(envName: 'MY_KEY2')
  static const MY_KEY2 = _Env.MY_KEY2;
}
`

The named parameter 'envName' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'envName'.dart[undefined_named_parameter](https://dart.dev/diagnostics/undefined_named_parameter)

**Comment by techouse** [comment]
Duplicate of https://github.com/petercinibulk/envied/issues/5

**Comment by jtkeyva** [comment]
thank you!
