### ISSUE TITLE
How can I make it work with Github actions and it's environment variables?

### ISSUE THREAD

**Issue by 5hirish** [petercinibulk/envied#82]
I have added my environment secret variables (not checked in the .env file) in the GitHub repo settings hopping that it would work with my Flutter release work flow, except I get `Environment variable not found for field `mySecretApiKey`. Not sure why it is not able to pick up the environment variables from GitHub.

**Comment by techouse** [comment]
Please do not spam Github issues with general questions about setting up Github actions. Check StackOverflow or maybe how I do it [here](https://github.com/techouse/alfred-gitmoji/blob/master/.github/workflows/build.yml#L41).

**Comment by 5hirish** [comment]
I understand. But this is hardly spamming. It is natural for someone to confuse environment secrets as environment variables and wonder why envied is erroring `Environment variable not found for field 'mySecretApiKey'` when I have them defined. It would benefit having a little tip on GitHub Actions variables to > `.env`. Since it is an environment variable handling library it is a relevant topic and question. But apologies for the inconvenience caused.
