### ISSUE TITLE
Could not format because the source could not be parsed

### ISSUE THREAD

**Issue by E-MRE** [petercinibulk/envied#89]
envied: ^0.5.3
envied_generator: ^0.5.3

My .env file like this:

```
BASE_URL = https://my-url
VERSION_HISTORY_URL=https://my-version-url
```

I can't generate _Environment class. What's wrong?

line 3, column 1 of .: This requires the 'class-modifiers' language feature to be enabled.

3 │ final class _Environment {static const List<int> _enviedkeybaseUrl = <int>[3136852724, 28656277, 2960098785, 3026012087, 430810535, 3324963032, 1843384856, 2863196284, 3097640243, 559753871, 2006989818, 2206466610, 2879846058, 1784467592, 1000727155, 4293927033, 4071079281, 2584629344, 1852648612, 3734082644, 3650595602, 2661729487, 1908460665, ];

```
@Envied(name: 'Environment', path: 'environments/release.env', obfuscate: true)
class ReleaseEnvironment extends AppEnvironment {
  @override
  @EnviedField(varName: EnvironmentFieldKey.baseUrlKey)
  final String baseUrl = _Environment.baseUrl;

  @override
  @EnviedField(varName: EnvironmentFieldKey.apmCollectorUrlKey)
  final String apmCollectorUrl = _Environment.apmCollectorUrl;
...
...
...
}
```

**Comment by ThexXTURBOXx** [comment]
https://dart.dev/language/class-modifiers

You need at least Dart 3.0. Since you did not provide any information about your current installation, I would guess that you are using an outdated version of Dart/Flutter.

**Comment by E-MRE** [comment]
> https://dart.dev/language/class-modifiers
> 
> You need at least Dart 3.0. Since you did not provide any information about your current installation, I would guess that you are using an outdated version of Dart/Flutter.

Sorry about that. My sdk version is ```>=3.1.0 <4.0.0``` 

I was using envied: 0.3.0+3 a few months ago. I upgraded to 0.5.3 and this error occurred. I cleared cache & pubspec.lock files but it didn't work.

**Comment by ThexXTURBOXx** [comment]
No problem, but this is indeed weird behavior then.
Maybe there is a way to specifically turn off language features and this is what happened on your machine, but I don't know, sadly

**Comment by techouse** [comment]
> I cleared cache & pubspec.lock files but it didn't work.

Can you try

```bash
flutter clean
flutter packages get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
```

Does it still fail? What happens if you change
```dart
class ReleaseEnvironment extends AppEnvironment {
  // stuff
}
```
to
```dart
final class ReleaseEnvironment implements AppEnvironment {
  // stuff
}
```
Using `implements` means that you'll probably have refactor quite some code.

**Comment by jas-brighte** [comment]
Having the same issue
my env.dart looks like 
```
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'BASE_SERVICE_URL')
  static const String baseServiceUrl = _Env.baseServiceUrl;
}

```

I have tried 

```
flutter clean
flutter packages get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
``` 

but these don't help

My setup

```Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"```

```Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (7 days ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1```

Any suggestions? even basic example from Readme is not working.

**Comment by jmadan** [comment]
Having the same issue
my env.dart looks like 
```
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'BASE_SERVICE_URL')
  static const String baseServiceUrl = _Env.baseServiceUrl;
}

```

I have tried 

```
flutter clean
flutter packages get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
``` 

but these don't help

My setup

```Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"```

```Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (7 days ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1```

Any suggestions? even basic example from Readme is not working.

**Comment by jmadan** [comment]
this seems like an issue not a question

**Comment by ThexXTURBOXx** [comment]
@jmadan `question` means that further information is required.

**Comment by luckyhandler** [comment]
I'm having the same issue after upgrading. Running 

```
flutter clean
flutter packages get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
```

didn't help.

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

Dart Version
`Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"`

I just upgraded from
`envied: ^0.3.0` to
`envied: ^0.5.3`

**Comment by E-MRE** [comment]
> > I cleared cache & pubspec.lock files but it didn't work.
> 
> Can you try
> 
> ```shell
> flutter clean
> flutter packages get
> dart run build_runner clean
> dart run build_runner build --delete-conflicting-outputs
> ```
> 
> Does it still fail? What happens if you change
> 
> ```dart
> class ReleaseEnvironment extends AppEnvironment {
>   // stuff
> }
> ```
> 
> to
> 
> ```dart
> final class ReleaseEnvironment implements AppEnvironment {
>   // stuff
> }
> ```
> 
> Using `implements` means that you'll probably have refactor quite some code.

When I clean build runner ```dart run build_runner clean```  envied generator worked successfully.

thanks alot bro.

**Comment by E-MRE** [comment]
> Having the same issue my env.dart looks like
> 
> ```
> import 'package:envied/envied.dart';
> 
> part 'env.g.dart';
> 
> @Envied(path: '.env')
> abstract class Env {
>   @EnviedField(varName: 'BASE_SERVICE_URL')
>   static const String baseServiceUrl = _Env.baseServiceUrl;
> }
> ```
> 
> I have tried
> 
> ```
> flutter clean
> flutter packages get
> dart run build_runner clean
> dart run build_runner build --delete-conflicting-outputs
> ```
> 
> but these don't help
> 
> My setup
> 
> `Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"`
> 
> ```
> Framework • revision bae5e49bc2 (7 days ago) • 2024-02-13 17:46:18 -0800
> Engine • revision 04817c99c9
> Tools • Dart 3.3.0 • DevTools 2.31.1```
> 
> Any suggestions? even basic example from Readme is not working.
> ```

What's the error message?

**Comment by E-MRE** [comment]
By the way my problem fixed. I didn't close issue because @jmadan looks like has a same error.

**Comment by XternalSoft** [comment]
Hello !
Same issue for me.

It's happened since flutter 3.19 (and dart 3.3.0) upgrade

I have tried
```
flutter clean
flutter packages get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
```
but these don't help too.

I have also added "final" on "env" class for test... but no...

**Comment by techouse** [comment]
Related https://github.com/lejard-h/chopper/issues/575#issuecomment-1958749367

> I tried again after removing the pubspec.lock file and it worked.
There seems to have been an issue with dart 3.0 in pubspec dependencies.

**Comment by XternalSoft** [comment]
Thanks @techouse , it's works now !

**Comment by kamilklyta** [comment]
This is due to an incompatible version of the `dart_style` package in the `pubspec.lock` file.
