### ISSUE TITLE
How to run specific enviornment based on command

### ISSUE THREAD

**Issue by affansk** [petercinibulk/envied#91]
Hey struggling with running specific enviornment like dev, staging, production.

i have setup exactly as in document , added extra 2 enviornment. i am not geting how will i run other 2 enviornment using command

**Comment by shanaka-sync** [comment]
I think it is up to us how we use it.
Eg:

@Envied(path: '.env.dev')
abstract class EnvDev {
    @EnviedField(varName: 'KEY1')
    static const key1 = _Env.key1;
}

@Envied(path: '.env.prd')
abstract class EnvPrd {
    @EnviedField(varName: 'KEY1')
    static const key1 = _Env.key1;
}

// in your app
use kReleaseMode to identify the mode then use EnvDev & EnvPrd accordingly. I hope this should work 😇

**Comment by affansk** [comment]
@shanaka-sync i drop this.. using dart define from file

**Comment by techouse** [comment]
> i have setup exactly as in document , added extra 2 enviornment. i am not geting how will i run other 2 enviornment using command

Using [flavors](https://docs.flutter.dev/deployment/flavors)
